不等式を8つ追加
delta2323/ml-formulas pull request #8
Opened 2018-06-16 22:28 UTC by ktrmnm

下記の8つを追加しました。また、READMEの対応部分に消し線を引きました。

最大値関係
- 最大不等式 (sub-Gaussian)
- Dudleyのエントロピーバウンド
- Slepianの不等式
- Sudakov minoration

極限定理関係
- DKW不等式
- Berry--Esseenの定理

凸幾何関係
- Brunn--Minkowski
- Prekopa--Leindler

2018-06-18 10:26 UTC, delta2323 requested changes

2018-06-18 10:26 UTC, delta2323 commented on src/brunn_minkowski.md
> +が成り立つ．ただし，集合 $A, B \subseteq \mathbb{R}^n$ に対して，$A + B$ はMinkowski和を表し，$\lambda A = \{ \lambda x: x \in A \}$ とする．
中括弧を入れる場合は， `\\{`，`\\}`としてください．

https://github.com/ktrmnm/ml-formulas/blob/9b2a48a358e16c2331639c838fb99a826a06ee0c/src/brunn_minkowski.md

![2018-06-18 18 11 41](https://user-images.githubusercontent.com/407052/41527759-140fa0fc-7323-11e8-8c94-427ddd767599.png)

2018-06-18 10:26 UTC, delta2323 commented on src/chaining.md
> +Dudley's entropy boundや，chainingと呼ばれている不等式は，(sub)-Gaussian processの最大値の期待値を，カバリングナンバーまたはパッキングナンバーの積分によって上から抑える形の不等式である．
これはコメントの方に移しても良いかもしれません．

2018-06-18 10:26 UTC, delta2323 commented on src/chaining.md
> +$T$ を可算集合として，$\{ X_t: t \in T \}$ を $T$ で添字づけられた平均0のガウス過程とする．つまり，それぞれの $X_t$ は同じ確率空間で定義された正規確率変数で，$\mathbb{E} X_t = 0$ を満たすものとする．$T$ に $X_t$ から誘導される擬距離 $d_X$ を
ditto（{は`\\{`で入力）

2018-06-18 10:26 UTC, delta2323 commented on src/chaining.md
> +上のステートメントは Talagrand (2014), (2.38) 式から取った．
コメントに書かれている文章が列挙しているので，リストとしてもいいかもしれません（その場合既にあるリストはもう一段ネストしたリストとなります）

2018-06-18 10:26 UTC, delta2323 commented on src/chaining.md
> +- $T$ を非可算集合にすることもできる．この場合，厳密には $\sup_{t \in T} X_t$ の部分の可測性を気にする必要がある．
何か十分条件が一つあると嬉しいかなと思います（Tがseparableならばよい？）

2018-06-18 10:26 UTC, delta2323 commented on src/chaining.md
> +よりタイトな不等式として，[Generic chaining](generic_chaining.md)と呼ばれるものが知られている．
リンク切れとなっています（今後追加予定？）

2018-06-18 10:26 UTC, delta2323 commented on src/dvoretzky_kiefer_wolfowitz.md
> +$X$ を $\mathbb{R}$ に値をとる任意の確率変数とし，$F: \mathbb{R} \to [0, 1]$ をその分布関数とする．$X_1, \ldots, X_n$ を $X$ の独立なコピーとして，$F_n$ をそれらの経験分布関数とする．このとき，ある定数 $0 < C < +\infty$ が存在して，任意の $t > 0$ に対して
Berry--Esseenでは，「X_1, ..., X_nをi.i.d.」としてX_1の条件を記述していました．そのあたりは統一した方が読みやすいかもしれません（そのあたりにルールとかあったほうが良いですかね？）

2018-06-18 10:26 UTC, delta2323 commented on src/dvoretzky_kiefer_wolfowitz.md
> +\mathrm{Pr}(\sqrt{n} \sup_{x \in \mathbb{R}} |F_n(x) - F(x)| > t) \leq C \exp( - 2 t^2)
自分はここの確率は`\mathbb{P}`としていました．特にそちらの記法にこだわりがあるわけではないですが，どちらかに統一したほうが良いかもしれません

2018-06-18 10:26 UTC, delta2323 commented on src/maximal_inequality.md
> +例えば，統計学ではカイ二乗分布の最大値に関する上界もよく利用される．$X_1, \ldots, X_n$ を，互いに独立とは限らない自由度 $p$ のカイ二乗確率変数とすると，
これは「最大不等式（カイ二乗分布）」などで独立の項目としても良いかと思います

2018-06-18 10:26 UTC, delta2323 commented on src/maximal_inequality.md
> +大きさの比較は[Slepianの不等式](slepian_inequality)を参照．
リンク切れ

2018-06-18 10:26 UTC, delta2323 commented on src/maximal_inequality.md
> +
コメントの部分はリストにしても良いと思います

2018-06-18 10:26 UTC, delta2323 commented on src/prekopa_leindler.md
> +Boucheron et al. Concentration inequalities: A Nonasymptotic Theory of Independence (2013)
リストにしたほうが良い？

2018-06-18 10:26 UTC, delta2323 commented on src/slepian_inequality.md
> +$X = (X_1, \ldots, X_n)$ と $Y = (Y_1, \ldots, Y_n)$ はそれぞれ平均 $0$ の正規分布を同時分布としてもつ確率変数列とする．$i, j \in \{ 1, \ldots, n \}$ について
ditto （{は`\\{`で入力）

2018-06-18 10:26 UTC, delta2323 commented on src/slepian_inequality.md
> +ガウス過程の最大値の期待値どうしを比較したり，下から抑えたいときに役立つ．[Sudakov minoration](sudakov_minoration.md)も参照．
出典は特になし？

2018-06-18 10:26 UTC, delta2323 commented on src/sudakov_minoration.md
> +$T$ を可算集合として，$\{ X_t: t \in T \}$ を $T$ で添字づけられた平均0のガウス過程とする．つまり，それぞれの $X_t$ は同じ確率空間で定義された正規確率変数で，$\mathbb{E} X_t = 0$ を満たすものとする．$T$ に $X_t$ から誘導される擬距離 $d_X$ を
ditto （{を`\\{`で入力）

2018-06-18 10:26 UTC, delta2323 commented on src/sudakov_minoration.md
> +Sudakov minorationによる下界はオーダーの意味でタイトではない場合がある．このギャップは[generic chaining](generic_chaining.md)と呼ばれる方法を利用することで埋まる．
リンク切れ（追記しますか？）

2018-06-18 10:26 UTC, delta2323 commented on src/sudakov_minoration.md
> +d_X(s, t) = (\mathbb{E} (X_s - X_t)^2)^{1/2}
下では`^{1/2}`をルートで表記しています．同じエントリの中では統一したほうが良いかなと思います

2018-06-18 10:27 UTC, delta2323 commented
@ktrmnm  コメントと出典の部分をリストとすべきかどうかを迷っています．意見を貰えるとありがたいです

2018-06-18 11:03 UTC, ktrmnm commented on src/chaining.md
> +Dudley's entropy boundや，chainingと呼ばれている不等式は，(sub)-Gaussian processの最大値の期待値を，カバリングナンバーまたはパッキングナンバーの積分によって上から抑える形の不等式である．
これは正直ちょっと迷ったところです（標準的なステートメントが選びにくいので）。ちょっと 移して読めるようにしてみます

2018-06-18 11:12 UTC, ktrmnm commented on src/chaining.md
> +- $T$ を非可算集合にすることもできる．この場合，厳密には $\sup_{t \in T} X_t$ の部分の可測性を気にする必要がある．
Tがseparable かつ X が $\Omega \times T \to \mathbb{R}$ として可測ならcompletion measurable、とかはあったと思います（その辺調べて書きます）

2018-06-18 11:13 UTC, ktrmnm commented on src/dvoretzky_kiefer_wolfowitz.md
> +\mathrm{Pr}(\sqrt{n} \sup_{x \in \mathbb{R}} |F_n(x) - F(x)| > t) \leq C \exp( - 2 t^2)
\mathbb{P} 了解です

2018-06-18 11:23 UTC, ktrmnm commented
@delta2323 出典はリストに統一でもいいですね。コメントは内容に依存しそうなので、ひとまず保留で…

2018-06-18 11:30 UTC, ktrmnm commented
@delta2323 「i.i.d.」のような用語は断りなく使用してよいでしょうか？ $X_1, \ldots, X_n$ はi.i.d.確率変数である、というような内容に対して定型句があると嬉しいです。

2018-06-18 11:38 UTC, delta2323 commented
まずは分量を書くことを優先したいので，ある程度コンセンサスがあるような記法はどんどん使って良いと思います（記法の統一の意味でもあとで用語集とか作ってもいいかもしれません）

2018-06-18 14:20 UTC, ktrmnm commented
おおむねレビューの通りに対応し、ついでにリンク切れの `generic_chaining.md` 追加しました。

2018-06-18 14:22 UTC, ktrmnm commented
texのアンダースコアが行内に並ぶと、github markdownの強調として解釈される現象がたまに起きるので、都合の悪いところは `\_` のようにエスケープしてます。（具体的にいつ起こるのかは理解してません）

2018-06-20 03:36 UTC, delta2323 approved these changes

2018-06-20 03:36 UTC, merged